from app.modules import CATEGORY_ORDER, CATEGORY_TITLES

print("ORDER:", CATEGORY_ORDER)
print("TITLES:", CATEGORY_TITLES)
print("COUNT ORDER:", len(CATEGORY_ORDER))
print("COUNT TITLES:", len(CATEGORY_TITLES))